#!/bin/bash
for i in {1..254}
do
        for j in {1..254}
        do
                ping 192.168.$i.$j -i 0.01 -c 1 &>>/dev/null && echo "192.168.$i.$j up" || echo "192.168.$i.$j down" &
        done
done
wait
